### ISSUE TITLE
Use the XDG Base Directory Specification

### ISSUE THREAD

**Issue by RobertAudi** [MordechaiHadad/bob#120]
Right now the directories are [hard-coded](https://github.com/MordechaiHadad/bob/blob/afcc3c220f3ca7d90c74f9dfc7a1da1478d786d1/src/helpers/directories.rs) for each OS.

I really like that the directories that are currently used – even though hard-coded – adheres to the standard directories of each OS:

- The [macOS Standard Directories](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html#//apple_ref/doc/uid/TP40010672-CH2-SW14)
- I don't use Windows, [this](https://learn.microsoft.com/en-us/windows/deployment/usmt/usmt-recognized-environment-variables#variables-that-are-recognized-only-in-the-user-context) is the best I could find.
- The [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) as a fallback.

It would be really cool if the paths were first checked using the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) and fall back to the OS-specific locations.

- `$HOME` for the home directory
- `$XDG_DATA_HOME` for the local data directory. `$HOME/.local/share` by default.
- `$XDG_CONFIG_HOME` for the config directory. `$HOME/.config` by default.

The downloads and installation directory are not part of the specification but can be defined as [custom directories](https://wiki.archlinux.org/title/XDG_user_directories#Creating_custom_directories) and can already be configured using `downloads_location` and `installation_location`.

As an alternative/bonus it would also be cool if the local data and config directories could be changed using environment variables – `$BOB_DATA_HOME` and `$BOB_CONFIG_HOME` maybe?

**Comment by MordechaiHadad** [comment]
Bob used to use XDG via [dirs](https://docs.rs/dirs/latest/dirs/index.html), but I eventually removed it due to #95 
I currently have no intention of adding it back, maybe in the future but not now as it seems like effort for no reward.

Regarding the bob env vars I am not a fan of this for several reasons:
1. Config file already exists(ofc you can't change the config file location this way but it is what it is) and adding another way of configuring bob seems a bit bloaty for me like how in cpp you can do 1 thing in 10 different ways.
2. To have the env vars persistent the user will have to interact with his system way too much which I am not really a fan of.

I can reconsider this at some point but not now.

**Comment by RobertAudi** [comment]
@MordechaiHadad How about a single environment variable to be able to change the location of the config file? I think that would be a reasonable compromise 🤔 

It won't change way of configuring bob and it would be completely optional and interaction with the system would be marginal.

As I said it would be cool to be able to do that as a "nice to have", but if that's not an option I can close the issue.

**Comment by MordechaiHadad** [comment]
@RobertAudi that is a good idea I agree

**Comment by MordechaiHadad** [comment]
@RobertAudi Added `$BOB_CONFIG` env var

**Comment by RobertAudi** [comment]
@MordechaiHadad Just checked it out and it works perfectly. Thanks a lot!
