### ISSUE TITLE
HTTP calls stall when compiling `reqwest` with `rustls`

### ISSUE THREAD

**Issue by aymanalqadhi** [MordechaiHadad/bob#140]
When installing `bob` normally via `cargo install ...`, running commands that require making HTTP calls get stalled most of the time.

However, where I try to make the exact same requests (same headers, scheme, etc.) using `curl`, they execute normally.

I think the problem is with the SSL/TLS implementation of `reqwest` with `rustls`. Because when I changed `rustls` to `default-tls` in `Cargo.toml` (which I think implies `native-tls*`) everything worked as expected.

**Comment by MordechaiHadad** [comment]
I moved bob some time ago to rustls because using default features caused me consistent issues that I have no actual control over, you should probably open an issue on reqwest/rustls repo and link this issue,
 
You could create a PR to add a cargo feature to bob that will allow custom compilation that uses the default features of reqwest.
