### ISSUE TITLE
Feature Request - Support environment variables in configuration paths

### ISSUE THREAD

**Issue by weilbith** [MordechaiHadad/bob#47]
Hey 👋🏾 

I would like to ask if it would be possible to allow using environment variables within the configuration file. Especially for the paths. I want to be able to do something like this:

```json
{
  "installation_location": "$XDG_DATA_HOME/bob/bin"
}
```

Is that hard to do in regards of multi OS support?

**Comment by MordechaiHadad** [comment]
Looks like a cool idea, it wouldn't be hard at all.
But from 0 to 10 how much do you want that feature? the reason I'm asking is because that when you have an ENV VAR as an argument you will have to parse the part that is the ENV VAR name, look for it, get the data and then connect it back to a string, and I'm unsure what the performance cost will be since you are reading the config everytime you invoke a command.

**Comment by weilbith** [comment]
I would argue that supporting environment variables are an almost "must" for any command-line tool. I mean else I would need to use absolute paths. This makes the configuration file "unsharable" via dotfiles or similar because it is special to OS and user.

I think performance isn't a too strong argument here. This tool doesn't run very often.  At least as long as there is no shell hook or so. And in any case, about how much performance cost do we talk here? Like 2ms every run? Even if it would be 300ms, it wouldn't be noticeable at all for this purpose here. At least from my point of view.

**Comment by MordechaiHadad** [comment]
@weilbith fair enough, I will start looking into this... but don't expect it right away as i'm currently working on 2 different PR and a personal project 😅
